frase=str(input('Qual o seu nome completo:')).strip()
n1=frase.upper()
print('Nome maiusculo: {} '.format(n1))
n2=frase.lower()
print('Nome minusculo: {}'.format(n2))
n3=len(frase)- frase.count(' ')
print('Total de letras na frase:{}'.format(n3))
n4=frase.find(' ')
print('Total de letras do primeiro nome:{}'.format(n4))