n=input('Digite algo:')
print('O tipo primitivo desse valor e',type(n))
print('E alfa numerico?',n.isalnum())
print('E alfabetico?',n.isalpha())
print('E um numero?',n.isnumeric())
print('Está em decimal?',n.isdecimal())
print('Esta em maiúsculo?',n.isupper())
print('Esta em minúsculo?',n.istitle())
print('Possui epaços?', n.isspace())
print('Esta capitalizada?',n.istitle())